// user types ////////////////////////////////=>
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// profile types ///////////////////////////////=>>
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";

// post types
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const PRODUCT_SUCCESSFULL = "PRODUCT_SUCCESSFULL";

// substribe user
export const SUBSCRIBE_USER = "SUBSCRIBE_USER";

// Category types
export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

// wish lists types
export const ADD_WISHLIST = "ADD_WISHLIST";
export const GET_WISHLIST = "GET_WISHLIST";
export const GET_WISHLISTS = "GET_WISHLISTS";
export const DELETE_WISHLIST = "DELETE_WISHLIST";

// PRODUCT REVIEWS TYPES
export const GET_REVIEWS = "GET_REVIEWS";
export const DELETE_REVIEW = "GET_REVIEWS";
export const ADD_REVIEW = "ADD_REVIEW";

//  RENTALS TYPES 
export const FETCH_RENTALS_SUCCESS = "FETCH_RENTALS_SUCCESS"; 
export const FETCH_RENTAL_BY_ID_SUCCESS = "FETCH_RENTAL_BY_ID_SUCCESS"; 
export const FETCH_RENTALS_INIT = "FETCH_RENTALS_INIT"; 
export const FETCH_RENTALS_FAIL = "FETCH_RENTALS_FAIL"; 

// UPDATE RENTAL TYPES 
export const UPDATE_RENTAL_SUCCESS = "UPDATE_RENTAL_SUCCESS"; 
export const UPDATE_RENTAL_FAIL = "UPDATE_RENTAL_FAIL"; 
export const RESET_RENTAL_ERRORS = "RESET_RENTAL_ERRORS"; 

// BOOKINGS TYPES
export const FETCH_USER_BOOKINGS_INIT = "FETCH_USER_BOOKINGS_INIT"; 
export const FETCH_USER_BOOKINGS_SUCCESS = "FETCH_USER_BOOKINGS_SUCCESS"; 
export const FETCH_USER_BOOKINGS_FAIL = "FETCH_USER_BOOKINGS_FAIL"; 

// BOOKING REVIEWS TYPES 
export const UPDATE_BOOKING_REVIEWS = "UPDATE_BOOKING_REVIEWS";
